services:
  backend:
    build:
      context: ./server
      target: development
    volumes:
      - ./server/src:/app/src:ro

  web:
    build:
      context: ./web
      target: development
    volumes:
      - ./web:/app

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - 80:80
