services:
  backend:
    build:
      context: ./server
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./server:/app:ro
    env_file:
      - ./server/.env
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    restart: always

  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  web:
    build:
      context: ./web
    ports:
      - 5173:5173
    volumes:
      - ./web:/app

volumes:
  mongodb_data:
  redis_data:
