services:
  backend:
    build:
      context: ./server
      target: development
    volumes:
      - ./server:/app:ro
    env_file:
      - ./server/.env
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    deploy:
      replicas: 3
    restart: always

  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  web:
    build:
      context: ./web
      target: development
    volumes:
      - ./web:/app

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    restart: always

volumes:
  mongodb_data:
  redis_data:
