services:
  backend:
    restart: always
    build:
      context: ./server
      target: development
    volumes:
      - ./server:/app:ro
    deploy:
      replicas: 3

  web:
    build:
      context: ./web
      target: development
    volumes:
      - ./web:/app

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
