services:
  server:
    build:
      context: ./server
      target: production
    env_file:
      - ./server/.env
    depends_on:
      - mongo
      - redis
    ports:
      - 3000:3000

  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  web:
    build:
      context: ./web
      target: production
    ports:
      - 8000:3000

volumes:
  mongodb_data:
  redis_data:
