services:
  server:
    build: ./server
    command: npm run dev
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - mongo
      - redis
    ports:
      - 3000:3000

  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  web:
    build: ./web
    volumes:
      - ./web:/app
    ports:
      - 8000:5173

volumes:
  mongodb_data:
  redis_data:
