services:
  backend:
    env_file:
      - ./server/.env
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started

  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  mongodb_data:
  redis_data:
