services:
  backend:
    build:
      context: ./server
      target: production

  web:
    restart: always
    build:
      context: ./web
      target: production
    ports:
      - 80:80
