services:
  server:
    build:
      context: ./server
      target: development
    volumes:
      - ./server/src:/app/src:ro

  web:
    build:
      context: ./web
      target: development
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - 8000:5173
